# Generated by Django 5.0.6 on 2025-01-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
