# Generated by Django 5.0.6 on 2025-04-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cnumber', models.CharField(max_length=30)),
                ('cemail', models.CharField(max_length=30)),
                ('cservice', models.CharField(max_length=30)),
                ('ccomment', models.CharField(max_length=100)),
            ],
        ),
    ]
